version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./php-fpm.sock:/var/run/php/php-fpm.sock
    links:
      - php-fpm
    environment:
      HTTP_MOD_REWRITE: "HTTP_MOD_REWRITE" # Variable para que PageKit no agregue index.php en las rutas

  php-fpm:
    image: php:7.4-fpm
    volumes:
      - ./src:/var/www/html
